# This is a basic workflow to help you get started with Actions

name: Main workflow

# Controls when the workflow will run
on: push
jobs:
  Build:
      runs-on: ubuntu-latest
      container: gradle:6-jdk11
      steps:
        - name: Clone down repository
          uses: actions/checkout@v4  
        - name: Build application 
        - run: ci/build-app.sh
        - name: Test
        - run: ci/unit-test-app.sh  

